CREATE TABLE IF NOT EXISTS consultorias (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  consultoria VARCHAR(255) NOT NULL,
  cliente VARCHAR(255) NOT NULL,
  tipo_contratacao ENUM('CLT', 'PJ', 'Cooperado') NOT NULL,
  data_inicio DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
